In [1]:
### Classification Dataset

import pandas as pd
import numpy as np

# From scikit library:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# Import data
data_f = pd.read_csv(r'Dataset/fetal_health.csv')
#oHeaders = list(data_f.columns.values)
#npData = data_f.to_numpy()

# Split Data
X = data_f.iloc[:,0:21] # All columns except the target
y = data_f.iloc[:,21] # Target vector
X_train, X_test, y_train, y_test = train_test_split(X,y) # Splits the data with 25% of the data set as the test set

#Scale Data
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train) # Fits the training data to the rest of the data, then scales it
X_test = sc_X.transform(X_test) # Just scales the data

In [5]:
## Model 1: kNN with k = 3

from sklearn.neighbors import KNeighborsClassifier

# Develop the model

KNNClassifier = KNeighborsClassifier(n_neighbors=3)
KNNClassifier.fit(X_train,y_train)

# Validate the model

KNNy_pred = KNNClassifier.predict(X_test)

KNNcm = confusion_matrix(y_test,KNNy_pred)
print(KNNcm)
print(accuracy_score(y_test,KNNy_pred))


[[405  11   2]
 [ 20  40   3]
 [  5   7  39]]
0.9097744360902256


In [3]:
## Model 2: Random Forest

from sklearn.ensemble import RandomForestClassifier

# Develop the model

RFClassifier = RandomForestClassifier(random_state=0)
RFClassifier.fit(X_train,y_train)

# Validate the model

RFy_pred = RFClassifier.predict(X_test)

RFcm = confusion_matrix(y_test,RFy_pred)
print(RFcm)
print(accuracy_score(y_test,RFy_pred))

[[416   2   0]
 [ 19  41   3]
 [  3   3  45]]
0.943609022556391


In [4]:
## Model 3: Multi-Layer Perceptron

from sklearn.neural_network import MLPClassifier

# Develop the model

MLPC = MLPClassifier(max_iter = 2000, random_state=1)
MLPC.fit(X_train,y_train)

# Validate the model

MLPy_pred = MLPC.predict(X_test)

MLPcm = confusion_matrix(y_test,MLPy_pred)
print(MLPcm)
print(accuracy_score(y_test,MLPy_pred))

[[403  14   1]
 [ 14  46   3]
 [  3   6  42]]
0.9229323308270677
