In [1]:
# Imports for file and from sklearn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import ExtraTreesClassifier

from sklearn.model_selection import train_test_split

from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import classification_report

In [2]:
#Reading, Splitting, and Setting data

data = pd.read_csv('fetal_health.csv') #read csv file
target = ['fetal_health']
pred = list(set(list(data.columns)) - set(target)) #set predictions to all data minus the target
data[pred] = data[pred]/data[pred].max()

X = data[pred].values # X = prediction values
y = data[target].values # y = target values

#splits 25% data to test set
xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [3]:
#Feature Selection 

X.shape
FeatureSelection = ExtraTreesClassifier(n_estimators = 20)
FeatureSelection = FeatureSelection.fit(X,y)
FeatureSelection.feature_importances_
TheModel = SelectFromModel(FeatureSelection,prefit = True)
X_new = TheModel.transform(X)
X_new.shape

C:\Users\sayma\AppData\Local\Temp/ipykernel_19032/3627454629.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  FeatureSelection = FeatureSelection.fit(X,y)


(2126, 10)

In [4]:
# Gradient Boosting Algorithm

from sklearn.ensemble import GradientBoostingClassifier
boost = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
boost.fit(xTrain, yTrain[:,0])
yPred1 = boost.predict(xTest)

# Print Results
print("Accuracy:", metrics.accuracy_score(yTest, yPred1),"\n")
print("Confusion Matrix \n",confusion_matrix(yTest, yPred1),"\n")
print("Classification Report \n",classification_report(yTest, yPred1))

Accuracy: 0.9061032863849765 

Confusion Matrix 
 [[317  11   5]
 [ 13  50   1]
 [  4   6  19]] 

Classification Report 
               precision    recall  f1-score   support

         1.0       0.95      0.95      0.95       333
         2.0       0.75      0.78      0.76        64
         3.0       0.76      0.66      0.70        29

    accuracy                           0.91       426
   macro avg       0.82      0.80      0.81       426
weighted avg       0.91      0.91      0.91       426



In [5]:
# Nearest Neighbours Algorithm (n = 5)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(xTrain, yTrain[:,0])
yPred2 = knn.predict(xTest)

# Print Results
print("Accuracy:", metrics.accuracy_score(yTest, yPred2),"\n")
print("Confusion Matrix \n",confusion_matrix(yTest, yPred2))
print("Classification Report \n",classification_report(yTest, yPred2))

Accuracy: 0.9107981220657277 

Confusion Matrix 
 [[323   9   1]
 [ 16  44   4]
 [  4   4  21]]
Classification Report 
               precision    recall  f1-score   support

         1.0       0.94      0.97      0.96       333
         2.0       0.77      0.69      0.73        64
         3.0       0.81      0.72      0.76        29

    accuracy                           0.91       426
   macro avg       0.84      0.79      0.82       426
weighted avg       0.91      0.91      0.91       426



In [6]:
# Ridge Algorithm

from sklearn.linear_model import RidgeClassifier
ridge = RidgeClassifier()
ridge.fit(xTrain, yTrain[:,0])
yPred3 = ridge.predict(xTest)

# Print Results
print("Accuracy:", metrics.accuracy_score(yTest, yPred3),"\n")
print("Confusion Matrix \n",confusion_matrix(yTest, yPred3))
print("Classification Report \n",classification_report(yTest, yPred3))

Accuracy: 0.8708920187793427 

Confusion Matrix 
 [[326   4   3]
 [ 31  32   1]
 [  5  11  13]]
Classification Report 
               precision    recall  f1-score   support

         1.0       0.90      0.98      0.94       333
         2.0       0.68      0.50      0.58        64
         3.0       0.76      0.45      0.57        29

    accuracy                           0.87       426
   macro avg       0.78      0.64      0.69       426
weighted avg       0.86      0.87      0.86       426

