In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

data = pd.read_csv('fetal_health.csv')
target_column = ['fetal_health']
predictors = list(set(list(data.columns)) - set(target_column))
data[predictors] = data[predictors]/data[predictors].max()

X = data[predictors].values
y = data[target_column].values

xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size = 0.25, random_state = 42)
xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size = 0.25, random_state = 42)


In [6]:
from sklearn.ensemble import GradientBoostingClassifier
boost = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
         max_depth=1, random_state=0).fit(xTrain, yTrain[:,0])
yPred = boost.predict(xTest)

In [7]:
from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(yTest, yPred))

Accuracy: 0.9078947368421053


In [10]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(yTest, yPred)
print(cm)

from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(yTest, yPred))

[[392  16   5]
 [ 15  66   1]
 [  4   8  25]]
Accuracy: 0.9078947368421053


In [9]:
from sklearn.metrics import classification_report
print (classification_report(yTest, yPred))

              precision    recall  f1-score   support

         1.0       0.95      0.95      0.95       413
         2.0       0.73      0.80      0.77        82
         3.0       0.81      0.68      0.74        37

    accuracy                           0.91       532
   macro avg       0.83      0.81      0.82       532
weighted avg       0.91      0.91      0.91       532

