In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

data = pd.read_csv('fetal_health.csv')
target_column = ['fetal_health']
predictors = list(set(list(data.columns)) - set(target_column))
data[predictors] = data[predictors]/data[predictors].max()

X = data[predictors].values
y = data[target_column].values

xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size = 0.25, random_state = 42)
xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size = 0.25, random_state = 42)


In [33]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(xTrain, yTrain[:,0])
yPred = knn.predict(xTest)

In [34]:
from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(yTest, yPred))

Accuracy: 0.9060150375939849


In [35]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(yTest, yPred)
print(cm)

from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(yTest, yPred))

[[399  12   2]
 [ 19  56   7]
 [  6   4  27]]
Accuracy: 0.9060150375939849


In [36]:
from sklearn.metrics import classification_report
print (classification_report(yTest, yPred))

              precision    recall  f1-score   support

         1.0       0.94      0.97      0.95       413
         2.0       0.78      0.68      0.73        82
         3.0       0.75      0.73      0.74        37

    accuracy                           0.91       532
   macro avg       0.82      0.79      0.81       532
weighted avg       0.90      0.91      0.90       532

