In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

data = pd.read_csv('fetal_health.csv')
target_column = ['fetal_health']
predictors = list(set(list(data.columns)) - set(target_column))
data[predictors] = data[predictors]/data[predictors].max()

X = data[predictors].values
y = data[target_column].values

xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size = 0.25, random_state = 42)
xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size = 0.25, random_state = 42)


In [48]:
from sklearn.linear_model import RidgeClassifier
ridge = RidgeClassifier()
ridge.fit(xTrain, yTrain[:,0])
yPred = ridge.predict(xTest)

In [49]:
from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(yTest, yPred))

Accuracy: 0.8778195488721805


In [50]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(yTest, yPred)
print(cm)

from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(yTest, yPred))

[[404   6   3]
 [ 37  42   3]
 [  7   9  21]]
Accuracy: 0.8778195488721805


In [51]:
from sklearn.metrics import classification_report
print (classification_report(yTest, yPred))

              precision    recall  f1-score   support

         1.0       0.90      0.98      0.94       413
         2.0       0.74      0.51      0.60        82
         3.0       0.78      0.57      0.66        37

    accuracy                           0.88       532
   macro avg       0.81      0.69      0.73       532
weighted avg       0.87      0.88      0.87       532

