In [1]:
# Imports for file and from sklearn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import classification_report

In [2]:
#Reading, Splitting, and Setting data

data = pd.read_csv('fetal_health.csv') #read csv file
target = ['fetal_health']
pred = list(set(list(data.columns)) - set(target)) #set predictions to all data minus the target
data[pred] = data[pred]/data[pred].max()

X = data[pred].values #X = prediction values
y = data[target].values #y = target values

#splits 25% data to test set
xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [3]:
# Gradient Boosting Algorithm

from sklearn.ensemble import GradientBoostingClassifier
boost = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
boost.fit(xTrain, yTrain[:,0])
yPred1 = boost.predict(xTest)

# Print Results
print("Accuracy:", metrics.accuracy_score(yTest, yPred1),"\n")
print("Confusion Matrix \n",confusion_matrix(yTest, yPred1),"\n")
print("Classification Report \n",classification_report(yTest, yPred1))

Accuracy: 0.9078947368421053 

Confusion Matrix 
 [[392  16   5]
 [ 15  66   1]
 [  4   8  25]] 

Classification Report 
               precision    recall  f1-score   support

         1.0       0.95      0.95      0.95       413
         2.0       0.73      0.80      0.77        82
         3.0       0.81      0.68      0.74        37

    accuracy                           0.91       532
   macro avg       0.83      0.81      0.82       532
weighted avg       0.91      0.91      0.91       532



In [4]:
# Nearest Neighbours Algorithm (n = 5)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(xTrain, yTrain[:,0])
yPred2 = knn.predict(xTest)

# Print Results
print("Accuracy:", metrics.accuracy_score(yTest, yPred2),"\n")
print("Confusion Matrix \n",confusion_matrix(yTest, yPred2))
print("Classification Report \n",classification_report(yTest, yPred2))

Accuracy: 0.9060150375939849 

Confusion Matrix 
 [[399  12   2]
 [ 19  56   7]
 [  6   4  27]]
Classification Report 
               precision    recall  f1-score   support

         1.0       0.94      0.97      0.95       413
         2.0       0.78      0.68      0.73        82
         3.0       0.75      0.73      0.74        37

    accuracy                           0.91       532
   macro avg       0.82      0.79      0.81       532
weighted avg       0.90      0.91      0.90       532



In [5]:
# Ridge Algorithm

from sklearn.linear_model import RidgeClassifier
ridge = RidgeClassifier()
ridge.fit(xTrain, yTrain[:,0])
yPred3 = ridge.predict(xTest)

# Print Results
print("Accuracy:", metrics.accuracy_score(yTest, yPred3),"\n")
print("Confusion Matrix \n",confusion_matrix(yTest, yPred3))
print("Classification Report \n",classification_report(yTest, yPred3))

Accuracy: 0.8778195488721805 

Confusion Matrix 
 [[404   6   3]
 [ 37  42   3]
 [  7   9  21]]
Classification Report 
               precision    recall  f1-score   support

         1.0       0.90      0.98      0.94       413
         2.0       0.74      0.51      0.60        82
         3.0       0.78      0.57      0.66        37

    accuracy                           0.88       532
   macro avg       0.81      0.69      0.73       532
weighted avg       0.87      0.88      0.87       532

